/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementsysytem;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author navee
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        dt(); // daet

        times(); // time

    }

    public void dt() {

        java.util.Date d = new java.util.Date();

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MMM-dd");

        String dd = sdf.format(d);
        lblDate.setText(dd);

    }
    // time
    Timer t;
    SimpleDateFormat st;

    public void times() {

        t = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.

                java.util.Date dt = new java.util.Date();
                st = new SimpleDateFormat("hh:mm:ss a");

                String tt = st.format(dt);
                lblTime.setText(tt);

            }
        });

        t.start();

    }

    String ustype;
    int idd;
    int newid;
    String uname;
    String usertype;

    public Main(int id, String usernme, String utype) {
        initComponents();
        dt(); // daet

        times(); // time

        //BC PICTURE
        ImageIcon myImage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/SRC/BC New(1366x768).jpg")));
        Image img1 = myImage.getImage();
        Image img2 = img1.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        jLabel3.setIcon(i);

        //Title PICTURE
        ImageIcon myImage21 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/SRC/Suwasewana Text.png")));
        Image img1001 = myImage21.getImage();
        Image img2001 = img1001.getScaledInstance(jLabel9.getWidth(), jLabel9.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon iii1 = new ImageIcon(img2001);

        jLabel9.setIcon(iii1);

        //logo PICTURE
        ImageIcon myImage2 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/SRC/LOGO omly new 2.png")));
        Image img100 = myImage2.getImage();
        Image img200 = img100.getScaledInstance(jLabel7.getWidth(), jLabel7.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon iii = new ImageIcon(img200);

        jLabel7.setIcon(iii);

        //BC PICTURE
        ImageIcon myImage5 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/SRC/Login BC.jpeg")));
        Image img15 = myImage5.getImage();
        Image img25 = img15.getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i5 = new ImageIcon(img25);
        jLabel4.setIcon(i5);

        //BC PICTURE
        ImageIcon myImage1 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/SRC/Main Page BC.jpeg")));
        Image img10 = myImage1.getImage();
        Image img20 = img10.getScaledInstance(jLabel8.getWidth(), jLabel8.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ii = new ImageIcon(img20);
        jLabel8.setIcon(ii);

        this.uname = usernme;
        lblUname.setText(uname);

        this.usertype = utype;
        lblUtype.setText(usertype);

        this.newid = id;

        idd = newid;

        ustype = lblUtype.getText();

        if (ustype.equals("Doctor")) {
            ReceptionistButton.setVisible(false);
            AdminButton.setVisible(false);
            DoctorButton.setVisible(true);


        } else if (ustype.equals("Receptionist")) {
            DoctorButton.setVisible(false);
            AdminButton.setVisible(false);

        } else if (ustype.equals("Admin")) {
            ReceptionistButton.setVisible(false);
            DoctorButton.setVisible(false);


        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        AdminButton = new javax.swing.JPanel();
        btnCreateUser = new javax.swing.JButton();
        btnAddNewReceptionist = new javax.swing.JButton();
        btnReport1 = new javax.swing.JButton();
        btnPaymentDetails = new javax.swing.JButton();
        btnViewDoctorDetails = new javax.swing.JButton();
        btnRoomDetails = new javax.swing.JButton();
        btnAddNewDoctor = new javax.swing.JButton();
        btnCreatRoom = new javax.swing.JButton();
        btnReceptionistDetails = new javax.swing.JButton();
        btnUserDetails = new javax.swing.JButton();
        btnDoctorShedule = new javax.swing.JButton();
        ReceptionistButton = new javax.swing.JPanel();
        btnAddNewPatient = new javax.swing.JButton();
        btnDoctorShedule1 = new javax.swing.JButton();
        btnViewChannelDetails = new javax.swing.JButton();
        btnRoomDetails1 = new javax.swing.JButton();
        btnReceptionistDetails1 = new javax.swing.JButton();
        btnCreateChannel = new javax.swing.JButton();
        btnPayment = new javax.swing.JButton();
        btnViewDoctorDetails1 = new javax.swing.JButton();
        btnViwePatientDetails = new javax.swing.JButton();
        btnPaymentDetails1 = new javax.swing.JButton();
        DoctorButton = new javax.swing.JPanel();
        btnCreatPrescription = new javax.swing.JButton();
        btnViewPrescription = new javax.swing.JButton();
        btnDoctorShedule2 = new javax.swing.JButton();
        btnViewChannelDetails1 = new javax.swing.JButton();
        btnDoctorShedule3 = new javax.swing.JButton();
        btnViwePatientDetails1 = new javax.swing.JButton();
        btnViewPrescription1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblUserImage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUname = new javax.swing.JLabel();
        lblUtype = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 344, 50));

        AdminButton.setBackground(new java.awt.Color(240, 240, 240,0));
        AdminButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreateUser.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCreateUser.setText("Creat User");
        btnCreateUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnCreateUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCreateUser.setMaximumSize(new java.awt.Dimension(180, 42));
        btnCreateUser.setMinimumSize(new java.awt.Dimension(180, 42));
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });
        AdminButton.add(btnCreateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 31, 180, 42));

        btnAddNewReceptionist.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAddNewReceptionist.setText(" Receptionist");
        btnAddNewReceptionist.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnAddNewReceptionist.setMaximumSize(new java.awt.Dimension(180, 42));
        btnAddNewReceptionist.setMinimumSize(new java.awt.Dimension(180, 42));
        btnAddNewReceptionist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewReceptionistActionPerformed(evt);
            }
        });
        AdminButton.add(btnAddNewReceptionist, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 31, 180, 42));

        btnReport1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReport1.setText("Report");
        btnReport1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnReport1.setMaximumSize(new java.awt.Dimension(180, 42));
        btnReport1.setMinimumSize(new java.awt.Dimension(180, 42));
        btnReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReport1ActionPerformed(evt);
            }
        });
        AdminButton.add(btnReport1, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 91, 180, 42));

        btnPaymentDetails.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPaymentDetails.setText("Payment Details");
        btnPaymentDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnPaymentDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentDetailsActionPerformed(evt);
            }
        });
        AdminButton.add(btnPaymentDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 152, 180, 41));

        btnViewDoctorDetails.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnViewDoctorDetails.setText("View Doctor Detailes");
        btnViewDoctorDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnViewDoctorDetails.setMaximumSize(new java.awt.Dimension(180, 42));
        btnViewDoctorDetails.setMinimumSize(new java.awt.Dimension(180, 42));
        btnViewDoctorDetails.setPreferredSize(new java.awt.Dimension(67, 23));
        btnViewDoctorDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDoctorDetailsActionPerformed(evt);
            }
        });
        AdminButton.add(btnViewDoctorDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 91, 180, 42));

        btnRoomDetails.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRoomDetails.setText("View Room Details");
        btnRoomDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnRoomDetails.setMaximumSize(new java.awt.Dimension(180, 42));
        btnRoomDetails.setMinimumSize(new java.awt.Dimension(180, 42));
        btnRoomDetails.setPreferredSize(new java.awt.Dimension(67, 23));
        btnRoomDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomDetailsActionPerformed(evt);
            }
        });
        AdminButton.add(btnRoomDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 31, 180, 42));

        btnAddNewDoctor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAddNewDoctor.setText("Doctor");
        btnAddNewDoctor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnAddNewDoctor.setMaximumSize(new java.awt.Dimension(180, 42));
        btnAddNewDoctor.setMinimumSize(new java.awt.Dimension(180, 42));
        btnAddNewDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewDoctorActionPerformed(evt);
            }
        });
        AdminButton.add(btnAddNewDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 31, 180, 42));

        btnCreatRoom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCreatRoom.setText("Create Room");
        btnCreatRoom.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnCreatRoom.setMaximumSize(new java.awt.Dimension(180, 42));
        btnCreatRoom.setMinimumSize(new java.awt.Dimension(180, 42));
        btnCreatRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatRoomActionPerformed(evt);
            }
        });
        AdminButton.add(btnCreatRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 91, 180, 42));

        btnReceptionistDetails.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReceptionistDetails.setText("View Receptionist Details");
        btnReceptionistDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnReceptionistDetails.setMaximumSize(new java.awt.Dimension(180, 42));
        btnReceptionistDetails.setMinimumSize(new java.awt.Dimension(180, 42));
        btnReceptionistDetails.setPreferredSize(new java.awt.Dimension(67, 23));
        btnReceptionistDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceptionistDetailsActionPerformed(evt);
            }
        });
        AdminButton.add(btnReceptionistDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 31, 180, 42));

        btnUserDetails.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUserDetails.setText("View User Details");
        btnUserDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnUserDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserDetailsActionPerformed(evt);
            }
        });
        AdminButton.add(btnUserDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 151, 180, 42));

        btnDoctorShedule.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDoctorShedule.setText("Doctor Shedule");
        btnDoctorShedule.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnDoctorShedule.setMaximumSize(new java.awt.Dimension(180, 42));
        btnDoctorShedule.setMinimumSize(new java.awt.Dimension(180, 42));
        btnDoctorShedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorSheduleActionPerformed(evt);
            }
        });
        AdminButton.add(btnDoctorShedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 151, 180, 42));

        jPanel1.add(AdminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 990, 220));

        ReceptionistButton.setBackground(new java.awt.Color(240, 240, 240,0));
        ReceptionistButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddNewPatient.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAddNewPatient.setText("Patient");
        btnAddNewPatient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnAddNewPatient.setMaximumSize(new java.awt.Dimension(180, 42));
        btnAddNewPatient.setMinimumSize(new java.awt.Dimension(180, 42));
        btnAddNewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewPatientActionPerformed(evt);
            }
        });
        ReceptionistButton.add(btnAddNewPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 31, 180, 42));

        btnDoctorShedule1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDoctorShedule1.setText("Doctor Shedule");
        btnDoctorShedule1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnDoctorShedule1.setMaximumSize(new java.awt.Dimension(180, 42));
        btnDoctorShedule1.setMinimumSize(new java.awt.Dimension(180, 42));
        btnDoctorShedule1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorShedule1ActionPerformed(evt);
            }
        });
        ReceptionistButton.add(btnDoctorShedule1, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 31, 180, 42));

        btnViewChannelDetails.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnViewChannelDetails.setText("View Channel  Details");
        btnViewChannelDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnViewChannelDetails.setMaximumSize(new java.awt.Dimension(180, 42));
        btnViewChannelDetails.setMinimumSize(new java.awt.Dimension(180, 42));
        btnViewChannelDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewChannelDetailsActionPerformed(evt);
            }
        });
        ReceptionistButton.add(btnViewChannelDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 31, 180, 42));

        btnRoomDetails1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRoomDetails1.setText("View Room Details");
        btnRoomDetails1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnRoomDetails1.setMaximumSize(new java.awt.Dimension(180, 42));
        btnRoomDetails1.setMinimumSize(new java.awt.Dimension(180, 42));
        btnRoomDetails1.setPreferredSize(new java.awt.Dimension(67, 23));
        btnRoomDetails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomDetails1ActionPerformed(evt);
            }
        });
        ReceptionistButton.add(btnRoomDetails1, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 31, 180, 42));

        btnReceptionistDetails1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReceptionistDetails1.setText("View Receptionist Details");
        btnReceptionistDetails1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnReceptionistDetails1.setMaximumSize(new java.awt.Dimension(180, 42));
        btnReceptionistDetails1.setMinimumSize(new java.awt.Dimension(180, 42));
        btnReceptionistDetails1.setPreferredSize(new java.awt.Dimension(67, 23));
        btnReceptionistDetails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceptionistDetails1ActionPerformed(evt);
            }
        });
        ReceptionistButton.add(btnReceptionistDetails1, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 31, 180, 42));

        btnCreateChannel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCreateChannel.setText("Create Channel");
        btnCreateChannel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnCreateChannel.setMaximumSize(new java.awt.Dimension(180, 42));
        btnCreateChannel.setMinimumSize(new java.awt.Dimension(180, 42));
        btnCreateChannel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateChannelActionPerformed(evt);
            }
        });
        ReceptionistButton.add(btnCreateChannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 91, 180, 42));

        btnPayment.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPayment.setText("Payment ");
        btnPayment.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnPayment.setMaximumSize(new java.awt.Dimension(180, 42));
        btnPayment.setMinimumSize(new java.awt.Dimension(180, 42));
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });
        ReceptionistButton.add(btnPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 91, 180, 42));

        btnViewDoctorDetails1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnViewDoctorDetails1.setText("View Doctor Detailes");
        btnViewDoctorDetails1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnViewDoctorDetails1.setMaximumSize(new java.awt.Dimension(180, 42));
        btnViewDoctorDetails1.setMinimumSize(new java.awt.Dimension(180, 42));
        btnViewDoctorDetails1.setPreferredSize(new java.awt.Dimension(67, 23));
        btnViewDoctorDetails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDoctorDetails1ActionPerformed(evt);
            }
        });
        ReceptionistButton.add(btnViewDoctorDetails1, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 91, 180, 42));

        btnViwePatientDetails.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnViwePatientDetails.setText("View Patient Details");
        btnViwePatientDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnViwePatientDetails.setMaximumSize(new java.awt.Dimension(180, 42));
        btnViwePatientDetails.setMinimumSize(new java.awt.Dimension(180, 42));
        btnViwePatientDetails.setPreferredSize(new java.awt.Dimension(67, 23));
        btnViwePatientDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViwePatientDetailsActionPerformed(evt);
            }
        });
        ReceptionistButton.add(btnViwePatientDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 91, 180, 42));

        btnPaymentDetails1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPaymentDetails1.setText("Payment Details");
        btnPaymentDetails1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnPaymentDetails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentDetails1ActionPerformed(evt);
            }
        });
        ReceptionistButton.add(btnPaymentDetails1, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 92, 180, 41));

        jPanel1.add(ReceptionistButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 990, 220));

        DoctorButton.setBackground(new java.awt.Color(240, 240, 240,0));
        DoctorButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreatPrescription.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCreatPrescription.setText("Create Prescription");
        btnCreatPrescription.setActionCommand("Prescription");
        btnCreatPrescription.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnCreatPrescription.setMaximumSize(new java.awt.Dimension(180, 42));
        btnCreatPrescription.setMinimumSize(new java.awt.Dimension(180, 42));
        btnCreatPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatPrescriptionActionPerformed(evt);
            }
        });
        DoctorButton.add(btnCreatPrescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 31, 180, 42));

        btnViewPrescription.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnViewPrescription.setText("View Prescription");
        btnViewPrescription.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnViewPrescription.setMaximumSize(new java.awt.Dimension(180, 42));
        btnViewPrescription.setMinimumSize(new java.awt.Dimension(180, 42));
        btnViewPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPrescriptionActionPerformed(evt);
            }
        });
        DoctorButton.add(btnViewPrescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 180, 42));

        btnDoctorShedule2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDoctorShedule2.setText(" Shedule Create");
        btnDoctorShedule2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnDoctorShedule2.setMaximumSize(new java.awt.Dimension(180, 42));
        btnDoctorShedule2.setMinimumSize(new java.awt.Dimension(180, 42));
        btnDoctorShedule2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorShedule2ActionPerformed(evt);
            }
        });
        DoctorButton.add(btnDoctorShedule2, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 31, 180, 42));

        btnViewChannelDetails1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnViewChannelDetails1.setText("View Channel  Details");
        btnViewChannelDetails1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnViewChannelDetails1.setMaximumSize(new java.awt.Dimension(180, 42));
        btnViewChannelDetails1.setMinimumSize(new java.awt.Dimension(180, 42));
        btnViewChannelDetails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewChannelDetails1ActionPerformed(evt);
            }
        });
        DoctorButton.add(btnViewChannelDetails1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 180, 42));

        btnDoctorShedule3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDoctorShedule3.setText("Doctor Shedule");
        btnDoctorShedule3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnDoctorShedule3.setMaximumSize(new java.awt.Dimension(180, 42));
        btnDoctorShedule3.setMinimumSize(new java.awt.Dimension(180, 42));
        btnDoctorShedule3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorShedule3ActionPerformed(evt);
            }
        });
        DoctorButton.add(btnDoctorShedule3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 180, 42));

        btnViwePatientDetails1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnViwePatientDetails1.setText("View Patient Details");
        btnViwePatientDetails1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnViwePatientDetails1.setMaximumSize(new java.awt.Dimension(180, 42));
        btnViwePatientDetails1.setMinimumSize(new java.awt.Dimension(180, 42));
        btnViwePatientDetails1.setPreferredSize(new java.awt.Dimension(67, 23));
        btnViwePatientDetails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViwePatientDetails1ActionPerformed(evt);
            }
        });
        DoctorButton.add(btnViwePatientDetails1, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 31, 180, 42));

        btnViewPrescription1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnViewPrescription1.setText("Take My Channels");
        btnViewPrescription1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnViewPrescription1.setMaximumSize(new java.awt.Dimension(180, 42));
        btnViewPrescription1.setMinimumSize(new java.awt.Dimension(180, 42));
        btnViewPrescription1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPrescription1ActionPerformed(evt);
            }
        });
        DoctorButton.add(btnViewPrescription1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 180, 42));

        jPanel1.add(DoctorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 990, 220));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/Login BC.jpeg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 360));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 1020, 360));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/LOGO omly new 2.png"))); // NOI18N
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 180, 230));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/Suwasewana Text.png"))); // NOI18N
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 530, 110));

        lblUserImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/LOGO FOR FRONT.jpg"))); // NOI18N
        jPanel6.add(lblUserImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 160, 120));

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Name");

        lblUname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUname.setForeground(new java.awt.Color(255, 255, 255));
        lblUname.setText("jLabel1");

        lblUtype.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUtype.setForeground(new java.awt.Color(255, 255, 255));
        lblUtype.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User Type");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(21, 21, 21)
                        .addComponent(lblUname))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(lblUtype)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblUname))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblUtype))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 221, 290, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/Main Page BC.jpeg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 310));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("jLabel4");
        jPanel3.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 260, 40));

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTime.setText("jLabel5");
        jPanel3.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, 240, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/BC New(1366x768).jpg"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        // TODO add your handling code here:
        User u = new User();
        u.setVisible(true);

    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void btnDoctorSheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorSheduleActionPerformed
        // TODO add your handling code here:
        ViewDoctorShedule z = new ViewDoctorShedule();
        z.setVisible(true);
    }//GEN-LAST:event_btnDoctorSheduleActionPerformed

    private void btnCreateChannelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateChannelActionPerformed
        // TODO add your handling code here:
        channel ch = new channel();
        ch.setVisible(true);

    }//GEN-LAST:event_btnCreateChannelActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        // TODO add your handling code here:
        Payments u = new Payments();
        u.setVisible(true);

    }//GEN-LAST:event_btnPaymentActionPerformed

    private void btnViwePatientDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViwePatientDetailsActionPerformed
        // TODO add your handling code here:
        viewPatient D = new viewPatient();
        D.setVisible(true);

    }//GEN-LAST:event_btnViwePatientDetailsActionPerformed

    private void btnViewChannelDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewChannelDetailsActionPerformed
        // TODO add your handling code here:
        viewchannel D = new viewchannel();
        D.setVisible(true);
    }//GEN-LAST:event_btnViewChannelDetailsActionPerformed

    private void btnAddNewDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewDoctorActionPerformed
        // TODO add your handling code here:
        Doctor v = new Doctor();
        v.setVisible(true);
    }//GEN-LAST:event_btnAddNewDoctorActionPerformed

    private void btnAddNewReceptionistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewReceptionistActionPerformed
        // TODO add your handling code here:
        Receptionist R = new Receptionist();
        R.setVisible(true);
    }//GEN-LAST:event_btnAddNewReceptionistActionPerformed

    private void btnReceptionistDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceptionistDetailsActionPerformed
        // TODO add your handling code here:
        ViewReceptionist R = new ViewReceptionist();
        R.setVisible(true);

    }//GEN-LAST:event_btnReceptionistDetailsActionPerformed

    private void btnAddNewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewPatientActionPerformed
        // TODO add your handling code here:
        Patient D = new Patient();
        D.setVisible(true);
    }//GEN-LAST:event_btnAddNewPatientActionPerformed

    private void btnViewDoctorDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDoctorDetailsActionPerformed
        // TODO add your handling code here:
        viewDoctor u = new viewDoctor();
        u.setVisible(true);
    }//GEN-LAST:event_btnViewDoctorDetailsActionPerformed

    private void btnCreatPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatPrescriptionActionPerformed
        // TODO add your handling code here:
        Prescription b = new Prescription();
        b.setVisible(true);
    }//GEN-LAST:event_btnCreatPrescriptionActionPerformed

    private void btnViewPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPrescriptionActionPerformed
        // TODO add your handling code here:
        ViewPrescription c = new ViewPrescription();
        c.setVisible(true);
    }//GEN-LAST:event_btnViewPrescriptionActionPerformed

    private void btnCreatRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatRoomActionPerformed
        // TODO add your handling code here:
        Rooms b = new Rooms();
        b.setVisible(true);
    }//GEN-LAST:event_btnCreatRoomActionPerformed

    private void btnRoomDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomDetailsActionPerformed
        // TODO add your handling code here:
        ViewRooms m = new ViewRooms();
        m.setVisible(true);
    }//GEN-LAST:event_btnRoomDetailsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(null, "Are you Want To Exit ?", "Exit", JOptionPane.YES_NO_OPTION);
        if (opt == 0) {
            this.dispose();
            new Login().setVisible(true);
        }
        //this.setVisible(false);

    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReport1ActionPerformed
        // TODO add your handling code here:
        ReportsJasper i = new ReportsJasper();
        i.setVisible(true);
    }//GEN-LAST:event_btnReport1ActionPerformed

    private void btnUserDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserDetailsActionPerformed
        // TODO add your handling code here:
        viewUsers v = new viewUsers();
        v.setVisible(true);
    }//GEN-LAST:event_btnUserDetailsActionPerformed

    private void btnPaymentDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentDetailsActionPerformed
        // TODO add your handling code here:
        viewPaymentDetails a = new viewPaymentDetails();
        a.setVisible(true);
    }//GEN-LAST:event_btnPaymentDetailsActionPerformed

    private void btnDoctorShedule1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorShedule1ActionPerformed
        // TODO add your handling code here:
        ViewDoctorShedule z = new ViewDoctorShedule();
        z.setVisible(true);
    }//GEN-LAST:event_btnDoctorShedule1ActionPerformed

    private void btnRoomDetails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomDetails1ActionPerformed
        // TODO add your handling code here:
         ViewRooms m = new ViewRooms();
        m.setVisible(true);
    }//GEN-LAST:event_btnRoomDetails1ActionPerformed

    private void btnReceptionistDetails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceptionistDetails1ActionPerformed
        // TODO add your handling code here:
        ViewReceptionist rp = new ViewReceptionist();
        rp.setVisible(true);
    }//GEN-LAST:event_btnReceptionistDetails1ActionPerformed

    private void btnViewDoctorDetails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDoctorDetails1ActionPerformed
        // TODO add your handling code here:
        viewDoctor u = new viewDoctor();
        u.setVisible(true);
    }//GEN-LAST:event_btnViewDoctorDetails1ActionPerformed

    private void btnPaymentDetails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentDetails1ActionPerformed
        // TODO add your handling code here:
        viewPaymentDetails a = new viewPaymentDetails();
        a.setVisible(true);
    }//GEN-LAST:event_btnPaymentDetails1ActionPerformed

    private void btnDoctorShedule2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorShedule2ActionPerformed
        // TODO add your handling code here:
        DoctorSchedule a = new DoctorSchedule();
        a.setVisible(true);
    }//GEN-LAST:event_btnDoctorShedule2ActionPerformed

    private void btnViewChannelDetails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewChannelDetails1ActionPerformed
        // TODO add your handling code here:
        viewchannel D = new viewchannel();
        D.setVisible(true);
    }//GEN-LAST:event_btnViewChannelDetails1ActionPerformed

    private void btnDoctorShedule3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorShedule3ActionPerformed
        // TODO add your handling code here:
        ViewDoctorShedule z = new ViewDoctorShedule();
        z.setVisible(true);
    }//GEN-LAST:event_btnDoctorShedule3ActionPerformed

    private void btnViwePatientDetails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViwePatientDetails1ActionPerformed
        // TODO add your handling code here:
         viewPatient D = new viewPatient();
        D.setVisible(true);
    }//GEN-LAST:event_btnViwePatientDetails1ActionPerformed

    private void btnViewPrescription1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPrescription1ActionPerformed
        // TODO add your handling code here:
        channeChooser ch = new channeChooser();
        ch.setVisible(true);
    }//GEN-LAST:event_btnViewPrescription1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminButton;
    private javax.swing.JPanel DoctorButton;
    private javax.swing.JPanel ReceptionistButton;
    private javax.swing.JButton btnAddNewDoctor;
    private javax.swing.JButton btnAddNewPatient;
    private javax.swing.JButton btnAddNewReceptionist;
    private javax.swing.JButton btnCreatPrescription;
    private javax.swing.JButton btnCreatRoom;
    private javax.swing.JButton btnCreateChannel;
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JButton btnDoctorShedule;
    private javax.swing.JButton btnDoctorShedule1;
    private javax.swing.JButton btnDoctorShedule2;
    private javax.swing.JButton btnDoctorShedule3;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnPaymentDetails;
    private javax.swing.JButton btnPaymentDetails1;
    private javax.swing.JButton btnReceptionistDetails;
    private javax.swing.JButton btnReceptionistDetails1;
    private javax.swing.JButton btnReport1;
    private javax.swing.JButton btnRoomDetails;
    private javax.swing.JButton btnRoomDetails1;
    private javax.swing.JButton btnUserDetails;
    private javax.swing.JButton btnViewChannelDetails;
    private javax.swing.JButton btnViewChannelDetails1;
    private javax.swing.JButton btnViewDoctorDetails;
    private javax.swing.JButton btnViewDoctorDetails1;
    private javax.swing.JButton btnViewPrescription;
    private javax.swing.JButton btnViewPrescription1;
    private javax.swing.JButton btnViwePatientDetails;
    private javax.swing.JButton btnViwePatientDetails1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUname;
    private javax.swing.JLabel lblUserImage;
    private javax.swing.JLabel lblUtype;
    // End of variables declaration//GEN-END:variables
}
