/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagementsysytem;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author navee
 */
public class Rooms extends javax.swing.JFrame {

    /**
     * Creates new form Rooms
     */
    public Rooms() {
        initComponents();
        Connect();
        AutoID();
        patient_table();

        //BC PICTURE
        ImageIcon myImage1 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/SRC/BC.jpeg")));
        Image img10 = myImage1.getImage();
        Image img20 = img10.getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ii = new ImageIcon(img20);
        jLabel2.setIcon(ii);

        //Small panel PICTURE
        ImageIcon myImage10 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/SRC/UcreationBC.png")));
        Image img100 = myImage10.getImage();
        Image img200 = img100.getScaledInstance(jLabel8.getWidth(), jLabel8.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ii0 = new ImageIcon(img200);
        jLabel8.setIcon(ii0);
    }

    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    public void Connect() {

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gp_hms", "root", "");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    public final void AutoID() {
        try {
            java.sql.Statement s = con.createStatement();
            rs = s.executeQuery("SELECT MAX(Room_ID) FROM rooms");
            rs.next();
            String maxPatientNo = rs.getString("MAX(Room_ID)");
            if (maxPatientNo == null) {
                lblId.setText("RM001");
            } else {
                int id = Integer.parseInt(maxPatientNo.substring(2));
                id++;
                String newPatientNo = String.format("RM%03d", id);
                lblId.setText(newPatientNo);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void patient_table() {
        try {
            pst = con.prepareStatement("SELECT * FROM rooms");
            rs = pst.executeQuery();
            java.sql.ResultSetMetaData Rsm = rs.getMetaData();
            int c;
            c = Rsm.getColumnCount();

            DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
            df.setRowCount(0);

            while (rs.next()) {
                Vector v2 = new Vector();

                for (int i = 1; i <= c; i++) {
                    v2.add(rs.getString("Room_ID"));
                    v2.add(rs.getString("RoomType"));
                    v2.add(rs.getString("RoomCapacity"));
                    v2.add(rs.getString("RoomLocation"));
                    v2.add(rs.getString("RoomCharge"));
                    v2.add(rs.getString("RoomDescription"));
                }
                df.addRow(v2);

            }

        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRoomLocation = new javax.swing.JComboBox();
        txtRoomCapacity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRoomCharges = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        bynUpdate = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        txtRoomType = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Room Number", "Room Type", "Room Capacity", "RoomLocation", "Room Charge", "Room Description"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 970, 240));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Room Number");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 104, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Room Type");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 104, 20));

        txtRoomLocation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtRoomLocation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ground Floor", "1 st Foor", "2 nd Foor", "3 rd Foor", "4 th Floor", " " }));
        txtRoomLocation.setSelectedIndex(-1);
        txtRoomLocation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtRoomLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 262, 30));

        txtRoomCapacity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtRoomCapacity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRoomCapacityKeyTyped(evt);
            }
        });
        jPanel1.add(txtRoomCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 262, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Room Capacity");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Room Location");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 20));

        txtRoomCharges.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtRoomCharges.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRoomChargesKeyTyped(evt);
            }
        });
        jPanel1.add(txtRoomCharges, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 262, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Room Charge (Rs.)");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Room Description");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 20));

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        txtDescription.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(txtDescription);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 262, 120));

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 390, 50));

        bynUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bynUpdate.setText("Update");
        bynUpdate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        bynUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bynUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(bynUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 390, 50));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Delete");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 390, 50));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Exit");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 390, 50));

        lblId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 130, 30));

        txtRoomType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtRoomType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Private Rooms", "Semi-Private Rooms", "General Wards", "Isolation Rooms", "Pediatric Rooms" }));
        txtRoomType.setSelectedIndex(-1);
        txtRoomType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtRoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 262, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/UcreationBC.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 660));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 1000, 660));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Room Creation");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 520, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/BC.jpeg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1380, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:

        if (lblId.getText() == null || txtRoomType.getSelectedItem() == null || txtRoomCapacity.getText() == null || txtRoomLocation.getSelectedItem() == null || txtRoomCharges.getText() == null || txtDescription.getText() == null) {
            JOptionPane.showMessageDialog(this, "Fill All Requared Information");
        } else {

            String rno = lblId.getText();
            String rtype = (String) txtRoomType.getSelectedItem();
            String rcapa = txtRoomCapacity.getText();
            String rlocation = (String) txtRoomLocation.getSelectedItem();
            String rcharge = txtRoomCharges.getText();
            String rdescrip = txtDescription.getText();
            String Status = "Avaliable";

            try {
                pst = con.prepareStatement("INSERT INTO rooms (Room_ID,RoomType,RoomCapacity,RoomLocation,RoomCharge,RoomDescription,Statues) VALUES (?,?,?,?,?,?,?)");
                pst.setString(1, rno);
                pst.setString(2, rtype);
                pst.setString(3, rcapa);
                pst.setString(4, rlocation);
                pst.setString(5, rcharge);
                pst.setString(6, rdescrip);
                pst.setString(7, Status);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, " Room successfully ADDED");

                AutoID();
                txtRoomCapacity.setText("");
                txtRoomCharges.setText("");
                txtDescription.setText("");
                patient_table();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, " Failed To ADD ");
                Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void bynUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bynUpdateActionPerformed
        // TODO add your handling code here:

        if (lblId.getText() == null || txtRoomType.getSelectedItem() == null || txtRoomCapacity.getText() == null || txtRoomLocation.getSelectedItem() == null || txtRoomCharges.getText() == null || txtDescription.getText() == null) {
            JOptionPane.showMessageDialog(this, "Fill All Requared Information");
            JOptionPane.showMessageDialog(this, "Select From Table");
        } else {

            String rno = lblId.getText();
            String rtype = (String) txtRoomType.getSelectedItem();
            String rcapa = txtRoomCapacity.getText();
            String rlocation = (String) txtRoomLocation.getSelectedItem();
            String rcharge = txtRoomCharges.getText();
            String rdescrip = txtDescription.getText();
            String Status = "Avaliable";

            try {
                pst = con.prepareStatement("UPDATE  rooms set RoomType=?,RoomCapacity=?,RoomLocation=?,RoomCharge=?,RoomDescription=?,Statues=? where Room_ID=?");
                pst.setString(1, rtype);
                pst.setString(2, rcapa);
                pst.setString(3, rlocation);
                pst.setString(4, rcharge);
                pst.setString(5, rdescrip);
                pst.setString(6, Status);
                pst.setString(7, rno);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, " Room successfully Updated");

                AutoID();
                txtRoomCapacity.setText("");
                txtRoomCharges.setText("");
                txtDescription.setText("");
                patient_table();

                btnAdd.setEnabled(true);

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, " Failed To Update ");
                Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_bynUpdateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel d1 = (DefaultTableModel) jTable1.getModel();
        int SelectIndex = jTable1.getSelectedRow();

        lblId.setText(d1.getValueAt(SelectIndex, 0).toString());
        txtRoomType.setSelectedItem(d1.getValueAt(SelectIndex, 1).toString());
        txtRoomCapacity.setText(d1.getValueAt(SelectIndex, 2).toString());
        txtRoomLocation.setSelectedItem(d1.getValueAt(SelectIndex, 3).toString());
        txtRoomCharges.setText(d1.getValueAt(SelectIndex, 4).toString());
        txtDescription.setText(d1.getValueAt(SelectIndex, 5).toString());

        btnAdd.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(null, "Are you Want To Delete ?", "Delete", JOptionPane.YES_NO_OPTION);
        if (opt == 0) {
            String pno = lblId.getText();

            try {
                pst = con.prepareStatement("DELETE FROM rooms WHERE  Room_ID=?");

                pst.setString(1, pno);

                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, " Room successfully Deleted");

                AutoID();
                txtRoomCapacity.setText("");
                txtRoomCharges.setText("");
                txtDescription.setText("");
                patient_table();

                btnAdd.setEnabled(true);

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, " Room Delete Unsuccessfully ");
                Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtRoomCapacityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRoomCapacityKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtRoomCapacityKeyTyped

    private void txtRoomChargesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRoomChargesKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtRoomChargesKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rooms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton bynUpdate;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtRoomCapacity;
    private javax.swing.JTextField txtRoomCharges;
    private javax.swing.JComboBox txtRoomLocation;
    private javax.swing.JComboBox txtRoomType;
    // End of variables declaration//GEN-END:variables
}
